# appveyor.yml
build: off # disable appveyor's automatic msbuild

stack: go 1.11
cache:
  - 'C:\Users\appveyor\go\pkg\mod'

environment:
  GO111MODULE: 'on'
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: '-t7z -m0=lzma -mx=9'
  PACK_PATH: '%APPVEYOR_BUILD_FOLDER%\artifacts\pack-%APPVEYOR_BUILD_NUMBER%-windows.exe'
  DOCKER_CERT_PATH: '%APPVEYOR_BUILD_FOLDER%\.travis'
  DOCKER_TLS_VERIFY: '1'
  DOCKER_HOST:
    secure: 9/n4Ey6XCzZt2TT5VP5cX5sugiR0WWV4bS6W3jo56M4= # currently in buildpack account
  file_secret:
    secure: nyH/ayJ9cnxXI05Vyri7ntns95Sqn/Q9+jGIrVAzZHU= # currently in buildpack account

artifacts:
  - path: artifacts

before_test:
  - choco install golang
  - go build -ldflags "-X main.Version=gitsha:%APPVEYOR_REPO_COMMIT%" -o %PACK_PATH% ./cmd/pack
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt %DOCKER_CERT_PATH%\key.appveyor.pem.enc -out %DOCKER_CERT_PATH%\key.pem -secret %file_secret%

test_script:
  - go test -count=1 -parallel=1 -v ./...
  - go test -count=1 -parallel=1 -v -tags=acceptance ./acceptance/...

